### PR TITLE
Cleanup of HW generation

### PR DESCRIPTION
**Pull request by schoeberl**

### CODE REVIEW

**Comment by schoeberl** [comment]
The one from yesterday has been reviewed and merged by Edward today in the morning. This is a new one with additional cleanup. I just continue to use the same remote branch. Wrong? Maybe those commits are too small, but this kind of change I prefer to do in small steps.

**Comment by lhstrh** [comment]
Not wrong at all. It's just that the changes look identical to the ones I saw had been merged. That's what confused me...

**Review by lhstrh — APPROVED** [review]

**Comment by schoeberl** [comment]
It needed a merge from master into this branch. Now you see only the new stuff. Looks like I need to learn how to live with PRs :-)

**Comment by lhstrh** [comment]
To my knowledge, this review policy on this particular repo is not new. I think @edwardcwang has been the sole maintainer of this repo for a while now. It has never really posed problems as Edward is usually quick to respond...

**Review by edwardcwang — APPROVED** [review]

**Pull request merged**
