### PR TITLE
Hold reset high first CC in Verilator emulation

### PR DESCRIPTION
**Pull request by erlingrj**
Set `reset` to `1` the very first clock cycle during emulation.

### CODE REVIEW

**Comment by sberkun** [comment]
Reset is read on the positive edge of the clock, so I believe it needs to be
```
while (!Verilated::gotFinish()) {
    top->clock = 1;
    top->eval();
    timestamp++;

    // Hold reset high the very first clock cycle.
    if (timestamp == 1) {
      top->reset = 1;
    } else {
      top->reset = 0;
    }

    ...
}
```

**Review by sberkun — CHANGES_REQUESTED** [review]
Reset is read on the positive edge of the clock, so I believe it needs to be
```
while (!Verilated::gotFinish()) {
    top->clock = 1;
    top->eval();
    timestamp++;

    // Hold reset high the very first clock cycle.
    if (timestamp == 1) {
      top->reset = 1;
    } else {
      top->reset = 0;
    }

    ...
}
```
(tested in the sleeper branch, not sure if there are any other non-zero RegInits to test this with)

**Comment by erlingrj** [comment]
The original proposal would have the reset high on the rising edge (eval() called with clock=1 and reset=1) of the first clock cycle. Didn't your program work with the original? Your suggestion drives reset on the second rising edge of the second clock cycle instead of the first

**Comment by sberkun** [comment]
Waveform with timestamp 0:
image

Waveform with timestamp 1:
image

**Comment by erlingrj** [comment]
Thanks for seeing that. I updated to assert reset for another cycle. I think I prefer that way over waiting and doing it a cycle later. Can you see that it works?

**Comment by sberkun** [comment]
did you mean `<=2` ? Timestamp increments twice in the loop. It does work with `<= 2`

Do you know if verilator simulates setup / hold time? I'm slightly worried about undefined behavior since reset is changing at the positive clock edge (when the signal is sampled), but I don't know enough about verilator to know if that might cause any issues. Given that it works its probably fine.

**Comment by erlingrj** [comment]
You are right! Setup and hold time is not a concept in Verilator AFAIK, it is purely synchronous

**Comment by erlingrj** [comment]
I updated the PR. Could you approve i, @sberkun

**Comment by sberkun** [comment]
@erlingrj Sorry, it looks like it still says `<= 1`, I believe it should be `<=2`

**Comment by erlingrj** [comment]
Yeah, I forgot to push... now I have finally done so

**Review by sberkun — APPROVED** [review]
sorry for the late reply, lgtm!

**Comment by erlingrj** [comment]
Actually, doing proper reset at the beginning exposed a bug in the threading library. Which is now fixed and we can soon merge this

**Pull request merged**
